[unstable]
codegen-backend = true
profile-rustflags = true

[build]
incremental = true
rustflags = ["-Z", "threads=8"]

[profile.dev]
opt-level = 1
strip = "debuginfo"
debug = "line-tables-only"
codegen-backend = "cranelift"

[profile.dev.package."*"]
debug = false
opt-level = 3

[env]
CC_KNOWN_WRAPPER_CUSTOM = "kache"
